language: node_js
node_js:
  - "lts/*"
script:
  - yarn lint
  - yarn build
  - yarn coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
